---
name: Rocky8

on:
  push:
    branches: [ master ]
    paths-ignores:
      - '*.md'

  pull_request:
    branches: [ master ]

jobs:
  Rocky9:

    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8.10
    
    steps:
    - uses: actions/checkout@v3
    - name: Install required packages
      run: |
        dnf install -y sudo git gcc gcc-c++ make autoconf libtool which
    - name: Setup
      run: |
        make github
        make install
    - name: Environment Check
      run: |
        make vars
        make exist
