---
name: Rocky9

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/debian*.yml'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/debian*.yml'

jobs:
  Rocky9:

    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:9

    steps:
    - uses: actions/checkout@v3
    - name: Install required packages
      run: |
        dnf install -y sudo git gcc gcc-c++ make autoconf libtool which
    - name: Setup
      run: |
        make github
    - name: Environment Check
      run: |
        make vars
        make exist
